apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: kube-system
  labels:
    k8s-app: nginx-ingress_Service
    kubernetes.io/cluster-service: 'true'
    #kubernetes.io/name: nginx-ingress
spec:
# Can also use LoadBalancer type
  type: NodePort
  ports:
  - name: http
    port: 8080
    nodePort: 30080
    targetPort: 80
    protocol: TCP
  selector:
    k8s-app: nginx-ingress-lb
