apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-logging 
  namespace: kube-system
spec:
  rules:
  - host: node74.ityunv.com
    http:
      paths:
      - backend:
          serviceName: kibana-logging 
          servicePort: 5601 
